version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -e .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Update submodules
          command: |
            . venv/bin/activate
            git submodule update --init
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "submodules"
      - run:
          name: Update repos.json
          command: |
            . venv/bin/activate
            make repos.json
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "repos.json" }}
          paths:
            - "repos.json"
      - add_ssh_keys:
          fingerprints:
            - "6c:f6:28:23:29:53:7c:22:a1:c0:cf:6b:ae:a9:cf:50"
      - run:
          name: Push repos.json back to repository
          command: |
              git status
